@extends('layouts.app')

@section('title', 'Pembayaran Berhasil')

@section('content')
<div class="payment-success-container">
    <div class="confetti-animation">
        <!-- Confetti elements will be generated by JS -->
    </div>
    
    <div class="success-card animate__animated animate__fadeInUp">
        <div class="success-icon animate__animated animate__bounceIn">
            <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
                <polyline points="22 4 12 14.01 9 11.01"></polyline>
            </svg>
        </div>
        
        <h1 class="success-title">Pembayaran Berhasil!</h1>
        <p class="success-message">
            Terima kasih telah melakukan pembayaran. Pemesanan Anda telah dikonfirmasi dan sedang diproses.
        </p>
        
        <div class="transaction-details">
            <div class="detail-item">
                <span class="detail-label">ID Transaksi</span>
                <span class="detail-value">{{ $pembayaran->referensi_pembayaran }}</span>
            </div>
            <div class="detail-item">
                <span class="detail-label">Tanggal</span>
                <span class="detail-value">{{ $pembayaran->waktu_pembayaran ? $pembayaran->waktu_pembayaran->format('d m Y H:i') : '-' }}</span>
                
            </div>
            <div class="detail-item">
                <span class="detail-label">Metode Pembayaran</span>
                <span class="detail-value">{{ ucfirst(str_replace('_', ' ', $pembayaran->metode_pembayaran)) }}</span>
            </div>
        </div>
        
        <div class="success-actions">
            <a href="{{ route('pemesanan.show', $pembayaran->id_pemesanan) }}" class="btn btn-primary">
                <i class="fas fa-receipt me-2"></i> Lihat Detail Pemesanan
            </a>
            <a href="{{ route('beranda') }}" class="btn btn-outline-secondary">
                <i class="fas fa-home me-2"></i> Kembali ke Beranda
            </a>
        </div>
        
        <div class="success-footer">
            <p>Butuh bantuan? <a href="#">Hubungi kami</a></p>
        </div>
    </div>
</div>

<style>
/* Custom CSS for premium design */
.payment-success-container {
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    background: linear-gradient(135deg, #f5f7fa 0%, #e4f0f8 100%);
    position: relative;
    overflow: hidden;
    padding: 2rem;
}

.confetti-animation {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    pointer-events: none;
    z-index: 1;
}

.success-card {
    background: white;
    border-radius: 16px;
    padding: 3rem;
    text-align: center;
    box-shadow: 0 15px 30px rgba(0, 0, 0, 0.1);
    max-width: 500px;
    width: 100%;
    position: relative;
    z-index: 2;
    border: 1px solid rgba(255, 255, 255, 0.3);
    backdrop-filter: blur(10px);
}

.success-icon {
    width: 100px;
    height: 100px;
    margin: 0 auto 1.5rem;
    display: flex;
    align-items: center;
    justify-content: center;
    background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
    border-radius: 50%;
    color: white;
    box-shadow: 0 10px 20px rgba(74, 172, 254, 0.3);
}

.success-title {
    font-size: 1.8rem;
    font-weight: 700;
    color: #2c3e50;
    margin-bottom: 1rem;
    background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}

.success-message {
    color: #7f8c8d;
    margin-bottom: 2rem;
    line-height: 1.6;
}

.transaction-details {
    background: #f8f9fa;
    border-radius: 12px;
    padding: 1.5rem;
    margin-bottom: 2rem;
    text-align: left;
}

.detail-item {
    display: flex;
    justify-content: space-between;
    margin-bottom: 0.75rem;
}

.detail-item:last-child {
    margin-bottom: 0;
}

.detail-label {
    color: #7f8c8d;
    font-weight: 500;
}

.detail-value {
    color: #2c3e50;
    font-weight: 600;
}

.success-actions {
    display: flex;
    flex-direction: column;
    gap: 1rem;
}

.btn {
    padding: 0.75rem 1.5rem;
    border-radius: 8px;
    font-weight: 600;
    transition: all 0.3s ease;
    display: flex;
    align-items: center;
    justify-content: center;
}

.btn-primary {
    background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
    border: none;
    color: white;
    box-shadow: 0 4px 15px rgba(74, 172, 254, 0.3);
}

.btn-primary:hover {
    transform: translateY(-2px);
    box-shadow: 0 6px 20px rgba(74, 172, 254, 0.4);
}

.btn-outline-secondary {
    border: 1px solid #dfe6e9;
    color: #636e72;
}

.btn-outline-secondary:hover {
    background-color: #f8f9fa;
    color: #2d3436;
}

.success-footer {
    margin-top: 2rem;
    color: #7f8c8d;
    font-size: 0.9rem;
}

.success-footer a {
    color: #4facfe;
    text-decoration: none;
    font-weight: 500;
}

/* Animations */
@keyframes fadeIn {
    from { opacity: 0; }
    to { opacity: 1; }
}

@keyframes slideInUp {
    from {
        transform: translateY(20px);
        opacity: 0;
    }
    to {
        transform: translateY(0);
        opacity: 1;
    }
}

.animate__animated {
    animation-duration: 1s;
    animation-fill-mode: both;
}

.animate__fadeInUp {
    animation-name: fadeInUp;
}

.animate__bounceIn {
    animation-name: bounceIn;
}

/* Responsive adjustments */
@media (max-width: 576px) {
    .success-card {
        padding: 2rem 1.5rem;
    }
    
    .success-title {
        font-size: 1.5rem;
    }
}
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    // Create confetti effect
    const confettiContainer = document.querySelector('.confetti-animation');
    const colors = ['#4facfe', '#00f2fe', '#ff9a9e', '#fad0c4', '#a18cd1'];
    
    for (let i = 0; i < 50; i++) {
        const confetti = document.createElement('div');
        confetti.style.position = 'absolute';
        confetti.style.width = Math.random() * 10 + 5 + 'px';
        confetti.style.height = Math.random() * 10 + 5 + 'px';
        confetti.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
        confetti.style.borderRadius = '50%';
        confetti.style.left = Math.random() * 100 + '%';
        confetti.style.top = -20 + 'px';
        confetti.style.opacity = Math.random() * 0.7 + 0.3;
        confetti.style.transform = `rotate(${Math.random() * 360}deg)`;
        
        const animationDuration = Math.random() * 3 + 2;
        confetti.style.animation = `fall ${animationDuration}s linear forwards`;
        
        confettiContainer.appendChild(confetti);
        
        // Create keyframes dynamically
        const keyframes = `
            @keyframes fall {
                to {
                    transform: translateY(100vh) rotate(${Math.random() * 360}deg);
                    left: ${Math.random() * 100}%;
                }
            }
        `;
        
        const style = document.createElement('style');
        style.innerHTML = keyframes;
        document.head.appendChild(style);
    }
    
    // Add micro-interactions
    const buttons = document.querySelectorAll('.btn');
    buttons.forEach(button => {
        button.addEventListener('mousedown', () => {
            button.style.transform = 'translateY(1px)';
        });
        
        button.addEventListener('mouseup', () => {
            button.style.transform = '';
        });
        
        button.addEventListener('mouseleave', () => {
            button.style.transform = '';
        });
    });
});
</script>
@endsection